### ISSUE TITLE
Sidebar doesn't open on Android 4

### ISSUE THREAD

**Issue by VladimirKalachikhin** [noerw/leaflet-sidebar-v2#19]
Subj, except Firefox.
The original sidebar-v2 works.

**Comment by noerw** [comment]
Could you provide more details on the issue?
What exactly does not work? Which browsers? What error message, if any, do you get on [this page](http://nickpeihl.github.io/leaflet-sidebar-v2/examples/index.html)?

**Comment by VladimirKalachikhin** [comment]
Not opens a sidebar in this page on Chrome 42 and default browser (with polyfills) in Android 4. "i" button works.

I no have a full DevTools on my computer, so I did not may debagging a problem.

**Comment by noerw** [comment]
Ok, i finally managed to check in the android browser on android 4 (api version 19). The error is:

```
Uncaught TypeError: Object function Object() { [native code] } has no method 'assign' http://www.npeihl.com/leaflet-sidebar-v2/js/leaflet-sidebar.js:49
```
