### ISSUE TITLE
Sidebar on right side causes attribution shift

### ISSUE THREAD

**Issue by DavidMoraisFerreira** [noerw/leaflet-sidebar-v2#52]
Hi,
I noticed that when using the sidebar on the right-hand side (https://noerw.github.io/leaflet-sidebar-v2/examples/position-right.html), the attribution text gets shifted to left instead of under the sidebar menu. I can reproduce this issue 100% of the time in Firefox 74 and Microsoft Edge.

![image](https://user-images.githubusercontent.com/16104349/77858025-3d778c00-7201-11ea-8658-e773140983c0.png)

**Comment by noerw** [comment]
This is intended behaviour, controls shift each other to the left or right, when they are in the same position slot.

To have attribution on the left side, add the attribution control manually to the map with the option `{ position: 'bottomleft' }`
